apiVersion: v1
kind: Service
metadata:
  name: quotes-service
spec:
  selector:
      app: quotes-service
  ports:
  - protocol: TCP
    port: 80 # The service port that is exposed
    targetPort: 5005 # The container port
  type: ClusterIP # Exposes the service on a cluster-internal IP