apiVersion: v1
kind: Service
metadata:
  name: generator-service
spec:
  selector:
    app: generator-service
  ports:
    - protocol: TCP
      port: 80 # The service port
      targetPort: 5050 # The container port
  type: ClusterIP
